### ISSUE TITLE
Create a GH action that fetches metrics into a file

### ISSUE THREAD

**Issue by liliana3186** [sbv-world-health-org-metrics/sbv-world-health-org-metrics#12]
```[tasklist]
### Tasks

- [ ] Interact with the GraphQL API using a script
- [ ] Save the data fetched in a file/s in the repo (ie: CSV, JSON)
- [ ] Create and configure a GH action that runs the script
- [ ] Document usage and requirements (such as secrets, env variables etc...)
```
